version: '3.8'

services:
  akshara:
    build: .
    container_name: akshara_ocr_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./cache.db:/app/cache.db
    restart: unless-stopped
